language: dart

dart:
# Install the latest stable release
  - stable
dart_task:
  - dartanalyzer: true
  - test: --platform vm
script:
  - pwd
  - sh test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)